config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/issues', to: 'issues#index'
  post '/comments', to: 'comments#create'
  delete '/comments', to: 'comments#destroy'
  patch '/comments', to: 'comments#update'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/votes',  to: 'votes#create'
  delete '/votes',  to: 'votes#destroy'
  post '/watches',  to: 'watches#create'
  delete '/watches',  to: 'watches#destroy'
  patch '/issues', to: 'issues#status_edit'
  put '/issues', to: 'issues#spam'
  put '/comments', to: 'comments#spam'
  post '/issues/:id', to: 'issues#delete_attachment'
  get 'auth/:provider/callback', to: 'sessions#google_create'
  get 'auth/failure', to: redirect('/')

  resources :issues
  resources :users
  root 'issues#index'
end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :user, :class_name => 'User', optional: true
	belongs_to :user, :class_name => 'User', optional: true
	belongs_to :kind
	belongs_to :priority
	belongs_to :status
	has_many :comments
	has_many :votes
	has_many :watches
	has_attached_file :attachment
	do_not_validate_attachment_file_type :attachment
	validates :title, presence: true

	before_save :default_values
	def default_values
		self.status_id ||= 1
		self.spam ||= false
	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index

    @issues = []
    filtered = false
    if params[:status]
      @status = Status.where('lower(name) = ?', params[:status].downcase).first 
      @issues = @issues.concat(Issue.where(status_id: @status.id))
      filtered = true
    end

    if params[:responsible]
      @user = User.where('lower(email) = ?', params[:responsible].downcase).first 
      @issues = @issues.concat(Issue.where(user_id_2: @user.id))
      filtered = true
    end
    if params[:responsiblename]
      @user = User.where('lower(name) = ?', params[:responsiblename].downcase).first
      @issues = @issues.concat(Issue.where(user_id_2: @user.id))
      filtered = true
    end
    if params[:kind]
      @kind = Kind.where('lower(name) = ?', params[:kind].downcase).first 
      @issues = @issues.concat(Issue.where(kind_id: @kind.id))
      filtered = true
    end
    if params[:priority]
      @priority = Priority.where('lower(name) = ?', params[:priority].downcase).first 
      @issues = @issues.concat(Issue.where(priority_id: @priority.id))
      filtered = true
    end

    if params[:watching]
      @user = User.where('lower(email) = ?', params[:watching].downcase).first
      @issues = @issues.concat(Issue.joins(:watches).where('watches.user_id' => @user))
      filtered = true
    end

    @issues = filtered ? @issues.uniq : Issue.all


    @watch = Watch.new

  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @comment = Comment.new
    @comments = Comment.where issue_id: params[:id]
    @comments = [] if @comments.nil?
    @vote = Vote.new
    @watch = Watch.new
    @status = Status.all
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.status_id = 1;
    respond_to do |format|
      if @issue.save
        watch = Watch.new
        watch.issue_id = @issue.id;
        watch.user_id = @issue.user_id;
        watch.save
        if (!@issue.user_id_2.nil?)
          if (@issue.user_id != @issue.user_id_2)
            watch2 = Watch.new
            watch2.issue_id = @issue.id;
            watch2.user_id = @issue.user_id_2;
            watch2.save
          end
        end
        format.html { redirect_to @issue }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_attachment
    @issue = Issue.find(params[:id])
    @issue.attachment = nil
    @issue.save
    redirect_to @issue
end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        if (!@issue.user_id_2.nil?)
          if (Watch.find_by(issue_id: @issue.id, user_id: @issue.user_id_2).nil?)
            watch = Watch.new
            watch.issue_id = @issue.id;
            watch.user_id = @issue.user_id_2;
            watch.save
          end
        end
        format.html { redirect_to @issue }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end

  def status_edit
    issue = Issue.find(params[:issue_id])
    issue.update(status_id: params[:status_id])
    redirect_to request.referer
  end

  def spam
    issue = Issue.find(params[:issue_id])
    issue.update(spam: !issue.spam)
    redirect_to request.referer
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:user_id, :user_id_2, :title, :description, :kind_id, :priority_id, :status_id, :spam, :attachment)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>
 
      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= form.label :title, :class => "form-label required" %>
    <%= form.text_field :title, id: :issue_title, :class => "lg-input" %>
  </div>
 
  <div class="field">
    <%= form.label :description, :class => "form-label"  %>
    <%= form.text_area :description, id: :issue_description , :class => "lg-textarea" %>
  </div>
 
  <div class="field">
    <%= form.label :assignee, :class => "form-label"  %>
    <div class="vertical">
      <%=form.collection_select :user_id_2, User.all, :id , :name_email, { :prompt => "Select user" }, { :class => "md-input", :id => 'form-asignee-select'} %>
      <%= link_to "Assign to me", 'javascript:;', :id => 'assign-me-btn', :class => "link margin-top-xsm", :my_id => current_user.id %>
    </div>
  </div>
 
 
  <div class="field">
    <%= form.label :kind, :class => "form-label required"  %>
     <%= form.collection_select :kind_id, Kind.all, :id, :name %>
  </div>
 
  <div class="field">
    <%= form.label :priority, :class => "form-label required"  %>
     <%= form.collection_select :priority_id, Priority.all, :id, :name %>
  </div>
 
  <div class="field">
    <%= form.label :attachment, :class => "form-label"  %>
    <%= form.file_field :attachment, :class => "lg-input"  %>
  </div>

 

 

app/views/issues/edit.html.erb
<div class="frame-wrapper">
    <h1>Issues</h1>
    <h3>Edit issue</h3>
 
	

    <div class="create-issue-form">
    	<%= form_with(model: @issue, local: true) do |form| %>
	    <%= render 'form', issue: @issue, form: form %>
	      <div class="actions">
    <!-- TODO: SUBMIT HIDDEN FIELDS -->
    		<div class="actions_wrapper">
		      <%= form.submit "Update issue", :class => "btn primary"%>
		      <%= link_to 'Back', issues_path, :class => "link margin-left-sm" %>
		    </div>
  		</div>
	    <% end %>
	</div>
	
</div>
 

app/views/issues/index.html.erb
<div class="frame-wrapper">
    <h1>Issues</h1>

    <div class="horizontal" style="align-items: center;">
      <span>FILTER BY: </span>
      <%= link_to 'All', issues_path, :class => "filter-btn transparent margin-left-sm" %>
      <%= link_to 'Open', issues_path(:status => 'open'), :class => "filter-btn transparent margin-left-sm" %>
      <%= link_to 'My issues', issues_path(:responsible => current_user.email), :class => "filter-btn transparent margin-left-sm" %>
      <%= link_to 'Watching', issues_path(:watching => current_user.email), :class => "filter-btn transparent margin-left-sm" %>
      <div class="filters-banner">
          <%= link_to 'Create issue', new_issue_path, :class => "filter-btn secondary" %>

      </div>
    </div>

    <h4>Issues (1 – <%= @issues.count %> of <%= @issues.count %>)</h4>

    <table class="issues-table">
      <thead>
        <tr>
          <th style="flex: 1;">Title</th>
          <th style="width: 45px;">T</th>
          <th style="width: 45px;">P</th>
          <th style="width: 100px;">Status</th>
          <th style="width: 100px;">Votes</th>
          <th style="width: 180px; text-overflow: ellipsis;">Assignee</th>
          <th style="width: 130px;">Created</th>
          <th style="width: 120px;">Updated</th>
          <th style="width: 30px"></th>
        </tr>
      </thead>

      <tbody>
        <% @issues.each do |issue| %>
          <tr class="<%= 'spam' if issue.spam? %>">
            <td class="title primary-text">
              <%= link_to "#" + issue.id.to_s + ": " + issue.title, issue %>    
            </td>
            <td>
              <%= link_to image_tag("kinds/" + Kind.find(issue.kind_id).name.downcase + ".svg"), issues_path(:kind => Kind.find(issue.kind_id).name) %>
            </td>
            <td>
              <!--<%= link_to Priority.find(issue.priority_id).name, issues_path(:priority => Priority.find(issue.priority_id).name) %>-->
              <%= link_to image_tag("priorities/" + Priority.find(issue.priority_id).name.downcase + ".svg", :class => "small-icon" ), issues_path(:priority => Priority.find(issue.priority_id).name) %>
            </td>
            <td class="status-cell">
              <span>
                <%= link_to Status.find(issue.status_id).name, issues_path(:status => Status.find(issue.status_id).name) %>
              </span>
            </td>
            <td class="votes-cell">
              <% if issue.votes.count > 0 %>
                  <span class="rounded-count blue"><%= issue.votes.count %></span>
              <% end %>
            </td>
            <td>
              <div class="issues-user-cell">
                <% if issue.user_id_2.present? %>
                <%= image_tag ("pictures/default.png") %>
                <%= link_to User.find(issue.user_id_2).name, issues_path(:responsible => User.find(issue.user_id_2).email) %>
                <% end %>
              </div>
            </td>
            <td><%= issue.created_at.to_formatted_s(:short) %></td>
            <td><%= issue.updated_at.to_formatted_s(:short) %></td>
            <td>
              <div class="watch-cell hidden">
                <%= form_for @watch, :html => {:id => "watch-form-" + issue.id.to_s} do |f| %>
                    <%= f.hidden_field :issue_id, value: issue.id %>
                    <%= f.hidden_field :user_id, value: current_user.id %>

                    <% if Watch.where(issue_id: issue.id, user_id: current_user.id).any? %>
                        <%= link_to image_tag("watches/watching.svg", :class => "small-icon" ), watches_path(user_id: current_user.id , issue_id: issue.id), method: :delete%>
                    <% else %>
                        <%= link_to image_tag("watches/not-watching.svg", :class => "small-icon" ), "", :onclick => "$('#watch-form-" + issue.id.to_s + "').submit()" %>
                    <% end %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

</div>

app/views/issues/new.html.erb
 <div class="frame-wrapper">
    <h1>Issues</h1>
    <h3>Create issue</h3>
 
	

    <div class="create-issue-form">
    	<%= form_with(model: @issue, local: true) do |form| %>
	    <%= render 'form', issue: @issue, form: form %>
          <%= form.hidden_field :user_id, :value => current_user.id%>
	      <div class="actions">
    <!-- TODO: SUBMIT HIDDEN FIELDS -->
    		<div class="actions_wrapper">
		      <%= form.submit "Create issue", :class => "btn primary"%>
		      <%= link_to 'Cancel', issues_path, :class => "link margin-left-sm" %>
		    </div>
  		</div>
	    <% end %>
	</div>
	
</div>
 

app/views/issues/show.html.erb
<div id="issue-detail" class="frame-wrapper">
  <h1><%= @issue.title %></h1>

  <div class="horizontal" style="align-items: center;">
    <span> Issue #<%= @issue.id %></span>
    <span class="issue-detail-status"> <%= Status.find(@issue.status_id).name %> </span>
    <div class="filters-banner">
      <%= link_to 'Create issue', new_issue_path, :class => "filter-btn secondary" %>
    </div>
  </div>

  <!-- Contenido issue + info + botones -->
  <div id="issue-detail-inner-wrapper">

    <div id="left-part">
      <div class="creator-wrapper <%= 'spam' if @issue.spam? %>">
        <%= image_tag ("pictures/default.png") %>
        <div class="creator-info">
          <div>
            <span>
              <%= link_to User.find(@issue.user_id).name, issues_path(:responsible => User.find(@issue.user_id).email), :class => "primary-text bold" %>
            </span> created an issue
            <span class="secondary-text sm-text"><%= @issue.created_at.to_formatted_s(:long) %></span>
          </div>
          <span class="margin-top-xsm"><%= @issue.description %></span>

          <div class="attachment <%= 'hidden' if !@issue.attachment? %>" >
            <div class="thumbnail">
              <div class="placeholder">
                <%= link_to image_tag("clip.png"), @issue.attachment.url(:original, false), :class => "placeholder" %>
              </div>
              <div class="delete-attachment-wrapper">
                <%= link_to image_tag("delete-attachment.svg", :class => 'delete-attachment-icon hidden'), @issue, method: :delete_attachment %>
              </div>
            </div>
            <div class="info">
              <%= link_to @issue.attachment.original_filename, @issue.attachment.url(:original, false), :class => 'link' if @issue.attachment? %>
            </div>
          </div>

        </div>
      </div>

      <h3>Comments (<%= @comments.length %>)</h3>

      <div id="comments-section">
        <% @comments.each do |comment| %>
            <div class="comment <%= 'spam' if comment.spam? %>" id="comment_<%= comment.id %>">
              <%= image_tag ('pictures/default.png') %>
              <div class="comment-info">
                <span class="primary-text bold"><%= (User.find_by id: comment[:user_id]).name %></span>
                <span class="comment-description"><%= comment[:description] %></span>

                <div class="edit-comment-form-wrapper hidden">
                  <%= form_tag(comments_path(comment_id: comment.id, issue_id: @issue.id), method: "PATCH") do %>
                      <%= text_area_tag :description, comment[:description], size: '24x6' %>
                      <div class="edit-comment-form-buttons">
                        <%= submit_tag('Comment', :class => "btn primary margin-left-sm") %>
                        <%= link_to 'Cancel', 'javascript:;', :class => "cancel-edit-comment-btn link margin-left-sm", "comment-id" => comment.id %>
                      </div>
                  <% end %>
                </div>


                <div class="comment-buttons">
                  <%= link_to 'Edit', 'javascript:;', :class => "edit-comment-btn", "comment-id" => comment.id %> -
                  <%= link_to comment.spam ? 'Approve - ' : 'Mark as spam - ', comments_path(comment_id: comment.id), method: :put %>
                  <%= link_to 'Delete', comments_path(comment_id: comment.id, issue_id: @issue.id), method: :delete %> -
                  <%= comment.created_at.to_formatted_s(:short) %>
                </div>
              </div>
            </div>
        <% end %>

        <div id="new-comment-area">
          <div>
            <%= image_tag ('pictures/default.png') %>
          </div>
          <div id="new-comment-form-wrapper">
            <%= form_for @comment do |f| %>
                <%= f.text_field :description, placeholder: 'What do you want to say?', size: '24x6', :id => "mock-textarea" %>
                <%= f.hidden_field :issue_id, value: @issue.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>

                <div id="create-comment-wrapper" class="hidden">
                  <%= f.text_area :description, placeholder: 'What do you want to say?', size: '24x6', :id => "valid-textarea" %>
                  <div id="new-comment-form-buttons">
                    <%= submit_tag('Comment', :class => "btn primary margin-left-sm") %>
                    <%= link_to 'Back', 'javascript:;', :class => "link margin-left-sm", :id => "create-comment-back" %>
                  </div>
                </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>

    <div id="right-part">
      <div class="buttons">
        <%= link_to "Resolve", issues_path(issue_id: @issue.id, status_id: 3), method: "PATCH", :class => "btn-md primary margin-left-sm" %>
        <%= link_to '#', :id => 'workflow-btn', :class => "btn-md secondary margin-left-sm dropdown-btn" do %>
            Workflow <%= image_tag ('arrow-down.png'), :class => "small-icon" %>
        <% end %>

        <div id="workflow-dropdown-btn" class="dropdown-wrapper">
          <% @status.each do |status| %>
              <%= link_to issues_path(issue_id: @issue.id, status_id: status.id), method: "PATCH" do %>
                  <div><%= status.name %></div>
              <% end %>
          <% end %>
        </div>


        <%= link_to '#', :id => 'more-btn', :class => "btn-xsm secondary margin-left-sm dropdown-btn" do %>
            More <%= image_tag ('arrow-down.png'), :class => "small-icon" %>
        <% end %>

        <div id="more-dropdown-btn" class="dropdown-wrapper">
          <%= link_to issues_path(issue_id: @issue.id), method: :put do %>
              <div><%= @issue.spam ? 'Approve' : 'Mark as spam' %></div>
          <% end %>
          <%= link_to @issue, method: :delete, data: {confirm: 'Are you sure?'} do %>
              <div>Delete</div>
          <% end %>
        </div>

        <%= link_to 'Edit', edit_issue_path(@issue), :class => "btn-xxsm secondary margin-left-sm" %>
      </div>
      <div class="issue-details-summary">

        <table id="details-fields-table">
          <tr>
            <td>Asignee</td>
            <td class="primary-text value">
              <% if @issue.user_id_2.present? %>
                  <%= image_tag("pictures/default.png", :class => "small-icon rounded") %>
                  <%= link_to User.find(@issue.user_id_2).name, issues_path(:responsible => User.find(@issue.user_id_2).email), :class => "margin-left-xsm underline-hover" %>
              <% else %>
                  -
              <% end %>
            </td>
          </tr>
          <tr>
            <td>Type</td>
            <td class="primary-text value">
              <%= image_tag("kinds/" + Kind.find(@issue.kind_id).name.downcase + ".svg") %>
              <%= link_to Kind.find(@issue.kind_id).name, issues_path(:kind => Kind.find(@issue.kind_id).name), :class => "margin-left-xsm underline-hover" %>
            </td>
          </tr>
          <tr>
            <td>Priority</td>
            <td class="primary-text value">
              <%= image_tag("priorities/" + Priority.find(@issue.priority_id).name.downcase + ".svg", :class => "small-icon") %>
              <%= link_to Priority.find(@issue.priority_id).name, issues_path(:priority => Priority.find(@issue.priority_id).name), :class => "margin-left-xsm underline-hover" %>
            </td>
          </tr>
          <tr>
            <td>Status</td>
            <td class="primary-text">
              <%= link_to Status.find(@issue.status_id).name, issues_path(:status => Status.find(@issue.status_id).name), :class => "underline-hover" %>
            </td>
          </tr>
          <tr>
            <td>Votes</td>
            <td class="primary-text value">
              <span class="rounded-count <%= Vote.where(issue_id: @issue.id, user_id: current_user.id).any? ? 'blue' : 'grey' %> "> <%= @issue.votes.count %></span>
              <div class="margin-left-xsm">
                <% if Vote.where(issue_id: @issue.id, user_id: current_user.id).any? %>
                    <%= link_to "Remove vote", votes_path(user_id: current_user.id, issue_id: @issue.id), method: :delete, :class => "underline-hover" %>
                <% else %>
                    <%= form_for @vote, :html => {:id => "vote-form"} do |f| %>
                        <%= f.hidden_field :issue_id, value: @issue.id %>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= link_to 'Vote for this issue', "", :onclick => "$('#vote-form').submit()", :class => "underline-hover" %>
                    <% end %>
                <% end %>
              </div>
            </td>
          </tr>
          <tr>
            <td>Watchers</td>
            <td class="primary-text value">
              <span class="rounded-count <%= Watch.where(issue_id: @issue.id, user_id: current_user.id).any? ? 'blue' : 'grey' %> "> <%= @issue.watches.count %></span>
              <div class="margin-left-xsm">
                <% if Watch.where(issue_id: @issue.id, user_id: current_user.id).any? %>
                    <%= link_to "Stop watching", watches_path(user_id: current_user.id, issue_id: @issue.id), method: :delete, :class => "underline-hover" %>
                <% else %>
                    <%= form_for @watch, :html => {:id => "watch-form"} do |f| %>
                        <%= f.hidden_field :issue_id, value: @issue.id %>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= link_to 'Watch this issue', "", :onclick => "$('#watch-form').submit()", :class => "underline-hover" %>
                    <% end %>
                <% end %>
              </div>
            </td>
          </tr>
        </table>

      </div>
    </div>
  </div>
  <!-- END Contenido issue + info + botones -->


  <%= link_to 'Back', issues_path, :class => "btn-sm secondary margin-top-lg" %>


</div>