config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/issues', to: 'issues#index'
  post '/comments', to: 'comments#create'
  delete '/comments', to: 'comments#destroy'
  patch '/comments', to: 'comments#update'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/votes',  to: 'votes#create'
  delete '/votes',  to: 'votes#destroy'
  post '/watches',  to: 'watches#create'
  delete '/watches',  to: 'watches#destroy'
  patch '/issues', to: 'issues#status_edit'
  put '/issues', to: 'issues#spam'
  put '/comments', to: 'comments#spam'
  post '/issues/:id', to: 'issues#delete_attachment'
  get 'auth/:provider/callback', to: 'sessions#google_create'
  get 'auth/failure', to: redirect('/')

  resources :issues
  resources :users
  root 'issues#index'
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	has_many :issues
	has_many :comments
	has_many :votes
	has_many :watches 

    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, 
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true

	def name_email
		self.name + " (" + self.email + ")"
	end

	def self.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end

	def self.new_token
    	SecureRandom.urlsafe_base64
  	end

  	def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest, User.digest(remember_token))
 	end

 	def authenticated?(remember_token)
 		return false if remember_digest.nil?
    	BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end


  	def forget
    	update_attribute(:remember_digest, nil)
  	end

    def self.from_omniauth(auth)
      where(email: auth.info.email).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.picture = auth.info.image
      user.save
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to issues_path
    else 
      render 'new'
    end
  end

  private

    def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div id="login-container">
  <div id="login-inner-wrapper">

    <p id="company-text">
      <%= image_tag ('atlassianicon.png') %>ASW
    </p>
    <p id="app-name-text">Issue Tracker</p>


    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.text_field :name, :placeholder => 'Full name', :class => 'btn-xxl input-field' %>
      <%= f.email_field :email, :placeholder => 'Email', :class => 'btn-xxl input-field' %>
      <%= f.password_field :password, :placeholder => 'Password', :class => 'btn-xxl input-field' %>
      <%= f.password_field :password_confirmation, :placeholder => 'Password confirmation', :class => 'btn-xxl input-field' %>
      <div id="buttons-wrapper">
        <%= f.submit 'Create account',:id => 'login-btn' %>
        <%= link_to 'Back', new_user_url, :class => "link margin-left-sm" %>
      </div>


  <% end %>
  </div>
</div>