config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/issues', to: 'issues#index'
  post '/comments', to: 'comments#create'
  delete '/comments', to: 'comments#destroy'
  patch '/comments', to: 'comments#update'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/votes',  to: 'votes#create'
  delete '/votes',  to: 'votes#destroy'
  post '/watches',  to: 'watches#create'
  delete '/watches',  to: 'watches#destroy'
  patch '/issues', to: 'issues#status_edit'
  put '/issues', to: 'issues#spam'
  put '/comments', to: 'comments#spam'
  post '/issues/:id', to: 'issues#delete_attachment'
  get 'auth/:provider/callback', to: 'sessions#google_create'
  get 'auth/failure', to: redirect('/')

  resources :issues
  resources :users
  root 'issues#index'
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menubar.html.erb
<% content_for(:menubar) do %>
    <div id="menubar">
      <div class="logo">
        <%= link_to image_tag("logo-upc.png"), issues_path %>
      </div>
      <div class="user-picture">
        <%= image_tag ("pictures/default.png"), :id => "menuUserImageButton" %>
        <div id="dropdown-menu">
            <div id="content">
              <span id="user-name"><%= current_user.name %></span>
              <%= link_to "Log out", logout_path, method: :delete %>
            </div>
        </div>
      </div>
    </div>
<% end %> 